name: weaving
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0-dev.2

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  badges: ^3.1.2
  clipboard_watcher: ^0.2.0
  cupertino_icons: ^1.0.2
  date_format: ^2.0.7
  dropdown_button2: ^2.3.9
  easy_refresh: ^3.3.2+4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_quill: ^8.5.1
  flutter_quill_extensions: ^0.6.7
  flutter_rating_stars: ^1.0.3+4
  flutter_riverpod: ^2.4.3
  flutter_smart_dialog: ^4.9.4
  flutter_tags_x: ^1.1.0
  hotkey_manager: ^0.1.8
  # https://isar.dev/zh/tutorials/quickstart.html
  image_cropper: ^5.0.0
  isar: ^3.1.0+1  # run `flutter pub run build_runner build` to generate codes
  isar_flutter_libs: ^3.1.0+1
  just_the_tooltip: ^0.0.12
  path_provider: ^2.1.1
  pretty_qr_code: ^3.0.0
  popup_card:
    git:
      url: https://github.com/guchengxi1994/popup_card
  qr_code_scanner: ^1.0.1
  quill_html_converter: ^0.0.1-experimental.1
  reorderables: ^0.6.0
  shared_preferences: ^2.2.2
  slang: ^3.25.0  # dart run slang
  slang_flutter: ^3.25.0
  window_manager: ^0.3.7

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  flutter_rename_app_plus3: ^1.2.4


dependency_overrides:  
  uuid: ^4.1.0
  popup_card:
    path: D:/github_repo/popup_card
  

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/emoji.txt
    - assets/empty.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
