name: weaving
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0-dev.9

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  badges: ^3.1.2
  calendar_date_picker2: ^0.5.3
  clipboard_watcher: ^0.2.0
  cupertino_icons: ^1.0.2
  dart_sm: ^0.1.4 
  date_format: ^2.0.7
  dotted_border: ^2.1.0
  # drag_and_drop_lists: ^0.3.3
  dropdown_button2: ^2.3.9
  easy_refresh: ^3.3.2+4
  equatable: ^2.0.5
  file_selector: ^1.0.1
  flutter:
    sdk: flutter
  flutter_expandable_fab: ^2.0.0
  flutter_quill: ^8.6.4
  flutter_quill_extensions: ^0.7.2
  flutter_rating_stars: ^1.0.3+4
  flutter_riverpod: ^2.4.3
  flutter_smart_dialog: ^4.9.4
  flutter_tags_x: ^1.1.0
  fsb_dart:
    git: 
      url: https://github.com/guchengxi1994/flutter_slint_bridge
      path: fsb_dart
  gantt_chart: ^0.3.0
  grouped_list: ^5.1.2
  hotkey_manager: ^0.1.8
  image_cropper: ^5.0.0
  # https://isar.dev/zh/tutorials/quickstart.html
  isar: ^3.1.0+1  # run `flutter pub run build_runner build` to generate codes
  isar_flutter_libs: ^3.1.0+1
  just_the_tooltip: ^0.0.12
  like_button: ^2.0.5
  logging: ^1.2.0
  path_provider: ^2.1.1
  pin_code_fields: ^8.0.1
  pretty_qr_code: ^3.0.0
  popup_card:
    git:
      url: https://github.com/guchengxi1994/popup_card
  qr_code_scanner: ^1.0.1
  quill_html_converter: ^0.0.1-experimental.1
  reorderables: ^0.6.0
  shared_preferences: ^2.2.2
  slang: ^3.25.0  # dart run slang
  slang_flutter: ^3.25.0
  super_clipboard: ^0.7.3
  taskboard:
    git:
      url: https://github.com/guchengxi1994/taskboard
  window_manager: ^0.3.7
  
  

dev_dependencies:
  build_runner: ^2.4.6
  build_runner_core: ^7.2.9
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  isar_generator: ^3.1.0+1
  flutter_rename_app_plus3: ^1.2.4
  flutter_launcher_icons: ^0.13.1  # flutter pub run flutter_launcher_icons
  msix: ^3.16.7


dependency_overrides:  
  analyzer: ^6.3.0
  meta: ^1.11.0
  uuid: ^4.1.0
  popup_card:
    path: D:/github_repo/popup_card
  
  fsb_dart:
    path: D:/github_repo/flutter_slint_bridge/fsb_dart
  
  taskboard:
    path: D:/github_repo/taskboard

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "./app_icon_2.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: "./app_icon_2.png"
    icon_size: 48 # min:48, max:256, default: 48
  linux:
    generate: true
    image_path: "./app_icon_2.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "./app_icon_2.png"
  

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/emoji.txt
    - assets/empty.png
    - assets/under_dev.png
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

msix_config:
  display_name: weaving
  publisher_display_name: xiaoshuyui
  identity_name: cn.xiaoshuyui
  msix_version: 0.0.0.8
  logo_path: D:/github_repo/weaving/icon.png

